version: 1.0.{build}

configuration: Release

platform: Any CPU

environment:
  COVERALLS_REPO_TOKEN:
    secure: K2NkAYD7KVzzaf9kcZHcKC4oXxbtndFQv

before_build:
- cmd: nuget restore Flatwhite.sln

build:
  project: Flatwhite.sln
  verbosity: minimal  

after_test: 
# generate report for NUnit testing framework:
    - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:packages/NUnit.Runners.2.6.4/tools/nunit-console.exe -register:user "-targetargs:""Tests\Flatwhite.Tests\bin\$env:CONFIGURATION\Flatwhite.Tests.dll"" /noshadow" -filter:"+[Flatwhite*]*" -output:opencoverCoverage.xml

    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover opencoverCoverage.xml
    
